### ISSUE TITLE
question about codes

### ISSUE THREAD

**Issue by Lizhiliang0726** [MengGuo/mix_initiative#1]
Sorry to be a bother . I have installed all environment setups from the Tiago ROS repo. However,I have some problems in understanding the four files  in folder “tiago” provided in package mix_initiative .I guess they may be related to the simulation environment .But I don't know where to place them or how to use them. Could you please make a  detailed introduction about the roslaunch of the simulation environment ? I will be appreciated if you can provide detailed instructions in the terminal while running the project (such as " roslaunch tiago_2dnav_gazebo localization.launch .......").

**Comment by MengGuo** [comment]
Hello, these environment setup should be included in the [TIAGO repo](http://wiki.ros.org/Robots/TIAGo)
